### ISSUE TITLE
Question about Density-Aware Radius Prediction

### ISSUE THREAD

**Issue by Eaphan** [PointsCoder/Pyramid-RCNN#1]
Thanks for your greak work.

I noticed that in the paper the grid feature is computed as below formulation:

![image](https://user-images.githubusercontent.com/21019429/134857529-3f05d5af-86da-4788-a148-1afc26d7cda0.png)
![image](https://user-images.githubusercontent.com/21019429/134857852-8826b995-ad3f-4c84-9c76-e68e25fa73f5.png)

But I don't find the corresponding code of  multiplication of s(i, r), can you help to explain it.

**Comment by PointsCoder** [comment]
Please refer to PyramidModuleV2 (line. 179) in pcdet/ops/pointnet2/pointnet2_stack/pointnet2_modules.py for the detailed implementation of the proposed 3 modules.

![image](https://user-images.githubusercontent.com/28640612/135051188-90ccddce-b456-4f00-8649-e6dedec03f59.png)

**Comment by Eaphan** [comment]
Thanks for your kind reminding.
