### ISSUE TITLE
Test models on Waymo

### ISSUE THREAD

**Issue by tdzdog** [PointsCoder/Pyramid-RCNN#4]
In paper, it says "We append another frame and use a larger voxel backbone" for test. What does it mean? How can I append the frame and which backbone should I use to reproduce the results on test leaderboard?

**Comment by PointsCoder** [comment]
@tdzdog You can use CarXL as the 3D backbone in rsn.py, and set MAX_SWEEPS = 2 in configs.

**Comment by PointsCoder** [comment]
Closed if no other questions.
