### ISSUE TITLE
How to use the KITTI test_set to evaluate model?

### ISSUE THREAD

**Issue by zhangwanjingjj** [PointsCoder/Pyramid-RCNN#9]
Thanks for your greate work! I want to use KITTI test set to evaluate the model. I modified DATA_SPLIT and INFO_PATH in the kitti_dataset.yaml, but the result shows that all the recalls are 0, and the mAP is not displayed.
![image](https://user-images.githubusercontent.com/97749065/161576056-35512000-fb6a-41d3-b833-f04868ca256f.png)
![image](https://user-images.githubusercontent.com/97749065/161575902-3536e02c-472e-486c-aa36-5180390a3342.png)

**Comment by PointsCoder** [comment]
@zhangwanjingjj test set has no labels. The test results can be submitted to the kitti website to see final  scores.
